name: _
publish_to: none
environment:
  sdk: ^3.12.0
workspace:
  - firebase_admin_sdk
  - firebase_functions_admin_sdk
  - firebase_admin_sdk_test
  - firebase_functions_admin_sdk_test
  - firebase_functions_admin_sdk_raw_test
  - firebase_functions_admin_sdk_test/functions
  - firebase_functions_admin_sdk_raw_test/functions
  - firebase_functions_admin_sdk_http
