name: tekartik_firebase_functions_admin_sdk_test
description: Test for firebase functions in admin sdk
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  dev_test: ">=1.0.3"
  http:
  path: ">=1.9.1"
  tekartik_firebase_functions_call:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: functions_call
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_dev_menu
  tekartik_firebase_emulator:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: firebase_emulator
  tekartik_firebase_functions_admin_sdk:
    git:
      url: https://github.com/tekartik/firebase_admin_sdk.dart
      path: firebase_functions_admin_sdk
  dev_build: ">=1.1.8+2"
  firebase_functions: ">=0.6.0"
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
  tekartik_common_utils:
    git: https://github.com/tekartik/common_utils.dart
  cv: ">=1.1.11"
  tekartik_firebase_functions_admin_sdk_http:
    git:
      url: https://github.com/tekartik/firebase_admin_sdk.dart
      path: firebase_functions_admin_sdk_http
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_http
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
  tekartik_firebase_auth_local:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_local
  tekartik_firebase_admin_sdk:
    git:
      url: https://github.com/tekartik/firebase_admin_sdk.dart
      path: firebase_admin_sdk
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
  tekartik_firebase_functions_test:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_test
  tekartik_firebase_functions_call_http:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: functions_call_http
dev_dependencies:
  lints: ">=6.1.0"
  test: ">=1.31.0"

resolution: workspace
